language: ruby
rvm:
  - 2.0.0

bundler_args: --without development

script:
- bundle exec rake db:setup
- bundle exec rake test
- bundle exec rake cucumber

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml_template_postgres config/database.yml
  - cp config/settings.yml_template config/settings.yml

before_install:
- export TZ=Europe/Berlin

addons:
  code_climate:
    repo_token: 34b145153ebfeb7e5f25626550843142b8b13cee0a81ddef10821aeb6b2dcd92
